urls.py
# -*- coding: utf-8 -*-
#
#       urls.py     
#       
#       Copyright 2011 David <kippeld@gmail.com>            
#                      Arnau <sacaix@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
# 
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', 'photos.views.index'),
    (r'^load/?$', 'photos.views.load'),
    (r'^upload/?$', 'photos.views.upload'),
    (r'^about/?$', 'photos.views.about'),
    # (r'^gll/', include('gll.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^static_media/(?P<path>.*)$', 'django.views.static.serve',
          {'document_root': '/home/kippel/src/gll/media'}),
     
     (r'^admin/', include(admin.site.urls)),
)

photos/models.py
# -*- coding: utf-8 -*-
#
#       models.py     
#       
#       Copyright 2011 David <kippeld@gmail.com>            
#                      Arnau <sacaix@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
# 
from django.db import models
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage()

# Create your models here.
class Photos(models.Model):
  name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nom:')
  description = models.TextField(blank=True, null=True, verbose_name=u'Descripció:')
  photo = models.ImageField(storage=fs, upload_to='photos', verbose_name='Fotografia*:')
  tags = models.CharField(max_length=200, verbose_name='Tags*:')
  
  def image_field(self):
    return "<img src='%s' width='120px' />" % self.photo.url

  image_field.short_description = 'Thumbnail'	
  image_field.allow_tags = True

photos/forms.py
# -*- coding: utf-8 -*-
#
#       forms.py     
#       
#       Copyright 2011 David <kippeld@gmail.com>            
#                      Arnau <sacaix@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
# 
from photos.models import Photos
from django.forms import ModelForm

class PhotosForm(ModelForm):
  class Meta:
    model = Photos

photos/views.py
# -*- coding: utf-8 -*-
#
#       views.py
#       
#       Copyright 2011 David <kippeld@gmail.com>
#                      Arnau <sacaix@gmail.com>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#       
#       
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from photos.models import Photos
from photos.forms import PhotosForm
from django.utils import simplejson
from django.template import Context, loader
from django.views.decorators.csrf import csrf_exempt
from django.template import RequestContext
from django.contrib import messages
import math

def gen_tag_from_photos(photos, threshold=0, maxsize = 3, minsize = 1):
  taglist = {}
  # agafo els tags i els conto
  for photo in photos:
    for tag in photo.tags.rsplit(' '):
      taglist[tag] = 1+taglist.get(tag,0);

  if len(taglist) == 0:
    return []
  
  # miro el maxim i el minim i elimino els que no superen el trheshold
  mincount, maxcount = 5000, 0;
  for (x, p) in taglist.items():
    if p <= threshold or len(x) <=2:
      del taglist[x]
      continue    
    
    if p > maxcount:
      maxcount=p
    if p < mincount:
      mincount=p
      
  constant = (math.log(maxcount -(mincount -1 )) /(maxsize -minsize or 1)  or 1)

  tagcloud = []
  for (x, p) in taglist.items():
     size = math.log(p - (mincount - 1))/constant + minsize
     tagcloud.append({
        'tag':x,
        'size': "%.2f" % size
     })
  
  return tagcloud  
  

def index(request):
  
  photos = Photos.objects.all()
  return render_to_response('main.html', {'tagcloud':gen_tag_from_photos(photos)}, context_instance = RequestContext(request))

def about(request):
  return render_to_response('about.html', context_instance = RequestContext(request))
 
@csrf_exempt 
def load(request):
  
  result = {'html':'', 'error':False, 'num':0}
    
  if request.method == 'POST':
    search = request.POST.get('search','')
    
    search = search.replace(',',' ').lower()
    
    photos = Photos.objects.filter(tags__search=search).order_by('?')[:10]
  
    
  
    if len(photos) >0:
      result['html'] = loader.get_template('galeria.html').render(Context({'photos':photos,'tagcloud':gen_tag_from_photos(photos)}))
  
    result['num'] = len(photos)
        
  return HttpResponse(simplejson.dumps(result) , mimetype='application/json')

#@login_required
def upload(request):
  if request.method=='POST':
    form = PhotosForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      
      messages.success(request, "La fotografia s'ha pujat correctament.")  
      
      return HttpResponseRedirect('/upload');
      
    else:
      messages.error(request, "No s'ha pujat la fotografia.")
      
  else:
    form = PhotosForm()
    
  return render_to_response('upload.html', {'form':form}, context_instance = RequestContext(request))    

templates/about.html
{% extends 'base.html' %}
{% block content %}
<!-- MEDIA_include_css upload -->
<div id='header'>
<h1>
<a href='/' class='titol-header'><img src='{{MEDIA_URL}}styles/titol00.png' border='0' width='452' height='72'></a>
</h1>
</div>

<div id='container'>
<div id='div-form-upload'>
<h2>Informació del Programa</h2>
<p class='info'>
Informació dels autors de programa.
</p>

<p>
<ul>
<li>Idea original: Fina de Lopez i <a href='http://www.elcolador.cat'>elColador</a></li>
<li>Maquetació: Arnau Bellavista (sacaix@gmail.com)</li>
<li>Programació: David Font (kippeld@gmail.com)</li>
</ul>
<a href='https://github.com/kippel/galeria-mites'>Codi Font</a> del programa
</p>
<p>
<div style='float:right;'><a href='/'>Tornar a la pàgina principal</a></div>
</p>
</div>
</div>

<div id='followTab'>

<a href='http://www.elcolador.cat'>
<img  src='http://www.elcolador.cat/logo00.gif' border='0' width='200' height='52'></a> 
 
</div>

{% endblock %}

templates/base.html
{% load i18n %}<!DOCTYPE html>
<html>
<head>
 <meta charset='utf-8' />
 <title>{% block title %}{% trans "Mitomanies" %}{% endblock %}</title>
 <!-- MEDIA_include_js jquery-1.5.1.min overlay.min toolbox.expose jquery.notify.min main -->
 <!-- MEDIA_compile_styles --><!-- MEDIA_include_css style -->
</head>
<body>{% block content %}{% endblock content %}

<div id="notify-container">
 <div id="basic-template"> 
  <a class="ui-notify-cross ui-notify-close" href="#">x</a>
  <h1>#{title}</h1>
  <p>#{text}</p>   
 </div>
 <div id="advanced-template"></div>
</div>
<!-- MEDIA_compile_scripts -->

{% if messages %}
  
<script type='text/javascript'>
{% for message in messages %}
   $('#notify-container').notify('create', {
        'title': '{{message.tags}}',
        'text': '{{ message }}'
   });
{% endfor %}
</script>   
{% endif %} 
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22972501-1']);
  _gaq.push(['_setDomainName', '.elcolador.cat']);
  _gaq.push(['_trackPageview']);
        
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>

templates/galeria.html
{% for photo in photos %}
<div id='galeria-photo' class='galeria-photo'>
<img class='fotografia' id='id-photo-{{photo.id}}' height='120px' name='photo-{{photo.id}}' src='{{photo.photo.url}}' rel='#overlay-{{photo.id}}'/>
</div>
{% endfor %}

{% for photo in photos %}
<div class='simple-overlay' id='overlay-{{photo.id}}' >
	<img src='{{photo.photo.url}}' />
	{% if photo.name != '' %}
	<div class='details'>
	<h3>{{ photo.name }}</h3>
	<p>{{ photo.description}}</p>
	</div>
	{% endif %}
</div>
{% endfor %}

<div id='galleria-tagcloud'>
{% include 'include/tagcloud.html' %}
</div>

templates/include/relatedlinks.html
<div id='div-related-links'>
<ul id='related-links'>
  <li><a href='/'>Pàgina principal</a></li>
    <li><a href='/about'>About...</a></li>
  </ul>
</div>
    

templates/include/tagcloud.html
{% for tag in tagcloud %}
<a href='#' class='tag' style='font-size:{{tag.size}}em'>{{tag.tag}}</a> 
{% endfor %}

templates/main.html
{% extends "base.html" %}
{% block content %}
<div id='header'>

	<a href='http://www.elcolador.cat'>
	<!--  -->
	<!-- <a href='/' class='titol-header'>Mito / en construcció</a> -->
	<a href='/' class='titol-header'><img src='{{MEDIA_URL}}styles/titol00.png' border='0' width='452' height='72'></a>

	Projecte paral·lel a <a href='http://www.elcolador.cat/mites'>Mites Contemporanis</a>.

</div>
<div id='container'>
<div id='div-search-header'>
   <div id='tx-search-wrapper'>
   <input id='tx-search-header' name='tx-search-header' type='text' value='' />
   <a href='#' class='button-header' id='bt-search-header'></a>
   <a href='/upload' class='a-upload-header'>Pujar Fotografies</a>
   </div>
</div>


<div id='div-info'>
<p>Aquest projecte és part d’un estudi científic-artístic al voltant del Mite.
El seu objectiu és compartir amb tots vosaltres, internautes interessats,
les relacions a l’hora estranyes, curioses, simples, al·lucinants,
transcendents i intranscendents que tenim amb el Mite.</p>
<p>Per tot això hem disposat d’una entrada amb la teva recerca i el resultat
que apareix correspon a totes aquelles imatges que altres usuaris,
neomitòlogs, han seleccionat en relació a la paraula que tu estàs buscant.
Continuarem augmentant els continguts d’aquesta web amb tots aquells que
estiguin interessats a participar amb les seves imatges i els seus
comentaris en aquest projecte. </p>
<p>Els conceptes i imatges que apareixen aquí estan imbricats i fan referència
als mites  amb els que representem part del nostre món i a nosaltres
mateixos. En aquest punt ens preguntem, és el món de les Idees el món del
Mite? I de ser així, ens tornem a preguntar, es pot viure sense els
mites?</p>
<p>La segona part d’aquest estudi avançarà en aquesta línia amb un objectiu
clar: transformar, envair, enderrocar o despullar mites. Plantejaments que
tant l’art como la ciència fan possibles des de processos d’acció diferents
i que aquest projecte combina.</p>
</div>
<div id='div-search'>
<h2>Termes de la cerca</h2>
<div style='vertical-align:0px'>
<input type='text' value='' id='tx-search-main' name='search' placeholder='Introduir tags...'/> <a class='button-principal' id='bt-search-main'></a>
<a href='/upload' class='a-upload-main'>Pujar Fotografies</a>
</div>
</div>

<div id='galeria'></div>
<div id='not_found' style='display:none'><h1>No s'han trobat imatges</h1></div>
<div id='main-tagcloud'>
{% include 'include/tagcloud.html'  %}
</div>

</div>
<br/><br/><br/>
<div id='followTab'>

<ul id='social-menu'>
 <li><a id='bt-twitter' class='button-social bt-twitter-search' href='#' target='_blank' title='Compartir la pàgina'>&nbsp;</a></li>
 <li><a id='bt-facebook' class='button-social bt-facebook-search' href='#' target='_blang' title='Compartir la pàgina'>&nbsp;</a></li>
</ul>


<a href='http://www.elcolador.cat'>
<img id='logo-colador' src='http://www.elcolador.cat/logo00.gif' border='0' width='200' height='52'></a>


</div>
{% include 'include/relatedlinks.html' %}
</div>
{%endblock%}

templates/upload.html
{% extends 'base.html' %}
{% block content %}
<!-- MEDIA_include_css upload -->
<div id='header'>
<h1>
<a href='/' class='titol-header'><img src='{{MEDIA_URL}}styles/titol00.png' border='0' width='452' height='72'></a>
</h1>
</div>
<div id='container'>
<div id='div-form-upload'>
<h2>Pujar Fotografies</h2>
<p class='info'>
Amb aquest formulari podeu pujar les fotografies a l'aplicació i aixi
participar.
</p>
<form name='fr_upload' id='id_fr_upload' method='post' enctype='multipart/form-data'>
	<table id='tb-upload'>
	<tr><td><label for='id_name'>{{form.name.label}}</label></td>
	    <td>{{form.name}}
	    	{{form.name.errors}}
	    </td>
	 </tr>
	
	<tr><td><label for='id_description'>{{form.description.label}}</label></td>
	    <td>{{form.description}}
	    	{{form.description.errors}}
	    </td>
	 </tr>
	<tr><td><label for='id_photo'>{{form.photo.label}}</label></td>
	    <td>{{form.photo}}
	    	{{form.photo.errors}}
	    </td>
	 </tr>
	<tr><td><label for='id_tags'>{{form.tags.label}}</label></td>
	    <td>{{form.tags}} {{form.tags.errors}}</td>
	 </tr>
	 
	</table>
		
{% csrf_token %}
<br>
<div class='buttons'>
<button type='submit' class='positive'>Pujar una Fotografia</button>
</div> o 
<a href='/'>Tornar a la pàgina principal</a>
<div style='clear:both'></div>
</form>
</div>
</div>
<div id='followTab'>
<ul id='social-menu'>
 <li><a id='bt-twitter' class='button-social' href='http://twitter.com/share?url=http%3A%2F%2Fmitomanies.elcolador.cat%2Fupload' target='_blank' title='Compartir la pàgina'>&nbsp;</a></li>
 <li><a id='bt-facebook' class='button-social' href='http://www.facebook.com/sharer.php?u=http%3A%2F%2Fmitomanies.elcolador.cat%2Fupload' target='_blank' title='Compartir la pàgina'>&nbsp;</a></li>
 </ul>

<a href='http://www.elcolador.cat'>
<img  src='http://www.elcolador.cat/logo00.gif' border='0' width='200' height='52'></a> 
 
</div>
{% include 'include/relatedlinks.html' %}
{% endblock %}